version: '3'

services:
  tutorial-java:
    container_name: javatodo
    restart: always
    image: rookout/tutorial-java
    build: .
    environment:
    - ROOKOUT_AGENT_HOST=rookout-agent
    ports:
    - "8080:8080"
    links:
    - rookout-agent
  rookout-agent:
    # The container name must be unique for each tutorial!
    container_name: rookout-agent-javatut
    image: rookout/agent
    environment:
    - ROOKOUT_TOKEN=$ROOKOUT_TOKEN
    - ROOKOUT_AGENT_TAGS=$ROOKOUT_AGENT_TAGS
    ports:
    - "7486:7486"
