version: '3'
services:
  tutorial-java:
    container_name: javatodo
    restart: always
    build: .
    environment:
      - ROOKOUT_AGENT_HOST=rookout-python-agent
    ports:
      - "5000:5000"
    links:
      - rookout-python-agent
#      todo: add golib agent
  rookout-python-agent:
    container_name: rookout-python-agent
    image: rookout/agent
    environment:
      - ROOKOUT_TOKEN=$ROOKOUT_TOKEN
      - ROOKOUT_AGENT_TAGS=pytut
    ports:
      - "7486:7486"
