version: 3

references:
  docker_auth: &docker_auth
    auth:
      username: _json_key
      password: $GOOGLE_AUTH

  checkout_default_wd: &checkout_default_wd
    checkout:
      path: ~/javatut

  load_cache: &load_cache
    restore_cache:
      keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  load_version: &load_version
    run: cat ~/javatut/workspace/VERSION >> $BASH_ENV

  setup_workspace: &setup_workspace
    attach_workspace:
      at: ~/javatut

  setup_docker_layer_caching: &setup_docker_layer_caching
    setup_remote_docker:
      docker_layer_caching: true

  setup_build_tools: &setup_build_tools
    run:
      command: |
        sudo su -
        mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        apt-get install python-setuptools python-dev build-essential
        easy_install pip
        pip install -e git+ssh://git@github.com/Rookout/build_tools.git#egg=rookout_build_tools

  setup_make: &setup_make
    run: apt install make

  filter_master: &filter_master
    filters:
      branches:
        only: master

  docker_login: &docker_login
    run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD


jobs:

  checkout_code_upver:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/javatut
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_build_tools
      - add_ssh_keys
      - run:
          command: |
            mkdir -p ~/javatut/workspace
            python -m rookout_build_tools.versioning.versions > ~/javatut/workspace/VERSION
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/javatut
      - persist_to_workspace:
          root: .
          paths:
            - workspace/VERSION

  build_and_push_javatut_image:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/javatut
    steps:
      - *load_cache
      - *setup_workspace
      - *load_version
      - *setup_make
      - *setup_docker_layer_caching
      - run: make build-jar-local
      - *docker_login
      - run: make build-and-upload

workflows:
  version: 2
  deploy-pipeline:
    jobs:
      - checkout_code_upver
      - build_and_push_javatut_image:
          requires:
            - checkout_code_upver
          <<: *filter_master
